# Generated by Django 5.2.6 on 2025-09-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.TextField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=20)),
                ('alcohol', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('employed', models.BooleanField(default=False)),
                ('criminal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.AlterModelTable(
            name='response',
            table='response',
        ),
        migrations.AlterField(
            model_name='response',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_sent', to='requests_app.adminuser'),
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='requests_app.offer')),
            ],
            options={
                'db_table': 'offer_images',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests_app.adminuser')),
            ],
            options={
                'db_table': 'refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='RelocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('stay_type', models.CharField(max_length=20)),
                ('accommodation_type', models.CharField(max_length=20)),
                ('for_whom', models.CharField(max_length=50)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
                ('pet', models.BooleanField(default=False)),
                ('pet_type', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('req_parking', models.BooleanField(default=False)),
                ('req_garage', models.BooleanField(default=False)),
                ('req_balcony', models.BooleanField(default=False)),
                ('req_terrace', models.BooleanField(default=False)),
                ('req_shops', models.BooleanField(default=False)),
                ('req_center', models.BooleanField(default=False)),
                ('req_hospital', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocation_requests', to='requests_app.requests')),
            ],
            options={
                'db_table': 'relocation_requests',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='requests_app.requests'),
        ),
        migrations.AlterField(
            model_name='response',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='requests_app.requests'),
        ),
        migrations.CreateModel(
            name='TimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_date', models.DateField()),
                ('know_duration', models.BooleanField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_requests', to='requests_app.requests')),
            ],
            options={
                'db_table': 'time_requests',
            },
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
