# Generated by Django 5.2.6 on 2025-09-07 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_adminuser_offer_requests_alter_response_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relocationrequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='relocationrequest',
            name='others',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='relocationrequest',
            name='pet_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relocationrequest',
            name='price_range',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='relocationrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='requests_app.requests'),
        ),
    ]
