# Generated by Django 5.2.6 on 2025-09-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_offerimage_image_requests_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='requestuser',
            name='password',
            field=models.CharField(default='temporary_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(default='temporary_password', upload_to='offer_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses_sent', to='requests_app.adminuser'),
        ),
    ]
